### ISSUE TITLE
API returns null for key userId and user

### ISSUE THREAD

**Issue by esdkrwl** [Krisseck/Hashtag-Wall-Server#11]
Hi,

I noticed that the API returns null for the keys "userId" and "user".

{
"id":4876,
"link":"https://instagram.com/p/ByDwc_qJ6er",
"image":"https://instagram.fham2-1.fna.fbcdn.net/vp/4e11180a1b33ea72df775b795978b21b/5D931DFA/t51.2885-15/e35/60418334_349955962371961_906103412093607567_n.jpg?_nc_ht=instagram.fham2-1.fna.fbcdn.net",
"caption":"#ct_espartanos #bjj #bjjforlife #jiujiteiros #jiujitsulifestyle👊 #jiujitsuportoalegre #artemarcial #ArteSuave #jiujiteiros #jiujiteirosincero #muaythaiportoalegre #muaythailifestyle #Muaythai",
"type":1,
"source_id":"2054698953741936555",
"created_at":"2019-05-29T19:47:04.000Z",
"updated_at":"2019-05-29T19:47:19.000Z",
"userId":null,
"user":null
}

According to the screenshots, the api should return the username. So I checked the demo and it indeed does not show the username anymore.

Is it intended or did Instagram changed some policies?

**Comment by esdkrwl** [comment]
The same problem is also occuring with twitter posts:

{"id":4843,"link":"https://twitter.com/gabymenta/status/1133821399255142400","image":"","caption":"&lt; #Anotala 👍😊 #viernes 7 - 17 hs","type":2,"source_id":1133821399255142400,"created_at":"2019-05-29T19:44:21.000Z","updated_at":"2019-05-29T19:44:27.000Z",**"userId":null,"user":null**}

**Comment by esdkrwl** [comment]
Hi,

I'm trying fixing it myself and would be very thankful, if you could provide some background information.

In instagram.js you are doing two calls on instagram, in order to grab the post and some userdata, like avatar, username und display name. According to the database model the post, including image and caption, and userdata, including username and avatar, should be stored in a mysql db. So I checked the tables and indeed - all these information are stored properly. So it's safe to assume, that making calls to instagram and saving those responses work as intended.

In the next step I looked into app.js at line 56 at which the resource /posts is provided. As far as I get this right, request on /posts should be answered with the last 30 posts and include user information according to the database model User. However there are no keys like **userId** or **user** saved and I have no clue, where this keys in the JSON response could come from.

So I checked the repo with grep for "userId" and noticed, that it is only mentioned in some imported node modules, but not in the project itself and that's why I assume, that line 69 does not work as it is supposed to.
On the other side, the resource /admin fetches user data the same way as /posts and the usernames are showing up to ignore specific user...

That's why I am somewhat confused and not sure, how to fix this problem myself, except reverting the repo till the api is returning the usernames again and redoing your commits afterwards.

I hope, that you could provide some help.

Best regards

**Comment by Krisseck** [comment]
Hey, this was bit tricky one.

It is due to a bug in `sequelize`, here is more information: https://github.com/sequelize/sequelize/issues/10857

In short, it's because we use underscored table fields, sequelize was looking for `UserId` field, even though it should be looking for `user_id`. 

I pushed a commit and it should now be fixed, you may need to create the database tables again.

**Comment by esdkrwl** [comment]
Works like a charm for me. Great job!
